apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cloudpak-deploy
spec:
  params:
  - name: issue_body
    description: Issue Body
  - name: issue_user
    description: User Name
  - name: issue_number
    description: Issue Number
  steps:
    - name: deploy-cloudpak
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/sh
        set -eu -o pipefail

        echo "$(params.issue_body)" > issue_body
        CP4WAIOPS_VERSION=$(grep cp4waiops.version issue_body | awk -F: '{print $NF}' | awk '{gsub(/^\s+|\$s+/, "");print}')
        AIMANAGER=$(grep cp4waiops.aiManager issue_body | awk -F: '{print $NF}' | awk '{gsub(/^\s+|\$s+/, "");print}')
        EVENTMANAGER=$(grep cp4waiops.eventManager issue_body | awk -F: '{print $NF}' | awk '{gsub(/^\s+|\$s+/, "");print}')

        curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd
        argo_route=openshift-gitops-server
        argo_secret=openshift-gitops-cluster
        sa_account=openshift-gitops-argocd-application-controller

        argo_pwd=$(oc get secret ${argo_secret} \
                    -n openshift-gitops \
                    -o jsonpath='{.data.admin\.password}' | base64 -d ; echo ) \
        && argo_url=$(oc get route ${argo_route} \
                      -n openshift-gitops \
                      -o jsonpath='{.spec.host}') \
        && argocd login "${argo_url}" \
              --username admin \
              --password "${argo_pwd}" \
              --insecure

        server_name=$(oc get OpenShiftFyre openshiftfyre-qb-large -n openshift-gitops -o jsonpath={.status.cluster.name}) \
        || {
          echo "OpenShiftFyre can not found."
          exit 1
        }
        SERVER=apps.$server_name.cp.fyre.ibm.com

        argocd app create $(params.issue_user)-cp4waiops-app \
        --sync-policy automatic \
        --project default \
        --repo https://github.com/IBM/cp4waiops-gitops.git \
        --path config/all-in-one \
        --revision release-3.3 \
        --dest-namespace openshift-gitops \
        --dest-server https://kubernetes.default.svc \
        --helm-set cp4waiops.targetRevision=release-3.3 \
        --helm-set argocd.cluster=openshift \
        --helm-set argocd.allowLocalDeploy=false \
        --helm-set rookceph.enabled=true \
        --helm-set cp4waiops.version=$CP4WAIOPS_VERSION \
        --helm-set cp4waiops.dockerUsername=cp \
        --helm-set cp4waiops.dockerPassword=REPLACE_IT \
        --helm-set cp4waiops.profile=small \
        --helm-set cp4waiops.aiManager.enabled=$AIMANAGER \
        --helm-set cp4waiops.aiManager.namespace=cp4waiops \
        --helm-set cp4waiops.aiManager.instanceName=aiops-installation \
        --helm-set cp4waiops.eventManager.enabled=$EVENTMANAGER \
        --helm-set cp4waiops.eventManager.clusterDomain=$SERVER \
        --helm-set cp4waiops.eventManager.namespace=noi

        curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d \
        "{\"body\": \"Created done\"}" \
        "https://api.github.ibm.com/repos/lyanwei/katamari-dev-issue-tracking/issues/$(params.issue_number)/comments"
