apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pr-validation-event-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-pr-validation-event-listener
    weight: 100
  wildcardPolicy: None
