apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: getting-started-triggertemplate
  namespace: getting-started
spec:
  params:
    - name: action
    - name: is_pr_merged
    - name: commit_sha
    - name: head_branch
    - name: base_branch
    - name: working_branch
    - name: pr_number
    - name: pr_repo_name
    - name: pr_repo_full_name
    - name: pr_repo_url
    - name: installation_id
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: hello-goodbye-run-
      spec:
        pipelineRef:
          name: hello-goodbye
        serviceAccountName: tekton-sa
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: getting-started-pipelinebinding
  namespace: getting-started
spec:
  params:
  - name: action
    value: $(body.action)
  - name: is_pr_merged
    value: $(body.pull_request.merged)
  - name: commit_sha
    value: $(extensions.commit_sha)
  - name: head_branch
    value: $(body.pull_request.head.ref)
  - name: base_branch
    value: $(body.pull_request.base.ref)
  - name: working_branch
    value: $(extensions.working_branch)
  - name: pr_number
    value: $(body.number)
  - name: pr_repo_name
    value: $(body.repository.name)
  - name: pr_repo_full_name
    value: $(body.repository.full_name)
  - name: pr_repo_url
    value: $(body.repository.html_url)
  - name: installation_id
    value: $(body.installation.id)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pr-validation-event-listener
spec:
  serviceAccountName: triggers-sa
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: getting-started-pipelinebinding
      interceptors:
        - params:
            - name: secretRef
              value:
                secretKey: token
                secretName: test-pipeline-el-secret
            - name: eventTypes
              value:
                - issue
          ref:
            kind: ClusterInterceptor
            name: github
      name: katamari-tests-pr-listener
      template:
        ref: getting-started-triggertemplate
