apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: getting-started-triggertemplate
spec:
  params:
    - name: issue_number
    - name: issue_user
    - name: issue_body
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cloudpak-deploy-run-
      spec:
        params:
          - name: issue_number
            value: $(tt.params.issue_number)
          - name: issue_user
            value: $(tt.params.issue_user)
          - name: issue_body
            value: $(tt.params.issue_body)
        pipelineRef:
          name: cloudpak
        serviceAccountName: triggers-sa
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: getting-started-pipelinebinding
spec:
  params:
  - name: issue_number
    value: $(body.issue.number)
  - name: issue_user
    value: $(body.issue.user.login)
  - name: issue_body
    value: $(body.issue.body)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pr-validation-event-listener
spec:
  serviceAccountName: triggers-sa
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: getting-started-pipelinebinding
      interceptors:
        - params:
            - name: secretRef
              value:
                secretKey: secretToken
                secretName: github-secret
            - name: eventTypes
              value:
                - issues
          ref:
            kind: ClusterInterceptor
            name: github
        - params:
            - name: filter
              value: 'body.action == "opened"'
          ref:
            kind: ClusterInterceptor
            name: cel
      name: issue-listener
      template:
        ref: getting-started-triggertemplate
