apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: getting-started-triggertemplate
spec:
  params:
    - name: action
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: hello-goodbye-run-
      spec:
        pipelineRef:
          name: hello-goodbye
        serviceAccountName: triggers-sa
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: getting-started-pipelinebinding
spec:
  params:
  - name: action
    value: $(body.action)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pr-validation-event-listener
spec:
  serviceAccountName: triggers-sa
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: getting-started-pipelinebinding
      interceptors:
        - params:
            - name: secretRef
              value:
                secretKey: secretToken
                secretName: github-secret
            - name: eventTypes
              value:
                - issues
          ref:
            kind: ClusterInterceptor
            name: github
        - params:
            - name: filter
              value: 'body.action == "opened"'
          ref:
            kind: ClusterInterceptor
            name: cel
      name: issue-listener
      template:
        ref: getting-started-triggertemplate
