apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cloudpak
spec:
  tasks:
  - name: cloudpak-deploy
    taskRef:
      name: cloudpak-deploy
  - name: goodbye
    runAfter:
     - cloudpak-deploy
    taskRef:
      name: goodbye
