apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cloudpak
spec:
  tasks:
  - name: ocp-provision
    taskRef:
      name: ocp-provision
  - name: cloudpak-deploy
    runAfter:
     - ocp-provision
    taskRef:
      name: cloudpak-deploy
